languageCode = "ru-ru"
title = "n-light"
baseURL = "http://n-light.by"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "light-bulb-brush.png"


	# Navigation
	[params.navigation]
		brand = "Богдан Назарук"

		[params.navigation.links]
			about     = "Обо мне"
			services  = "Услуги"
			portfolio = "Портфолио"
			contact   = "Контакты"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan = "Инженер-конструктор"
		subtitle = "<b>Специализация:</b> светотехника, литьевые и экструзионные детали, упаковка.<br><b>Опыт работы:</b> более 25 лет"
		buttonText = "Подробнее"


	# About section
	[params.about]
		headline    = "Обо мне"

		description = "<p>Конструированием осветительного оборудования занимаюсь с 1984 года и по настоящее время. За это время разработано значительное количество светильников с разными источниками света (лампы накаливания общего и специального назначения, люминесцентные лампы, газоразрядные лампы высокого давления, светодиоды), различного назначения (для наружного освещения, освещения производственных, торговых, офисных и жилых помещений, транспортных средств), для различных условий окружающей среды.</p>
		<p>Осведомлен о последних инновационных разработках в данной области, так как тесно сотрудничаю с компанией Vossloh-Schwabe (Германия) - поставщиком комплектующих к светильникам.  Имею опыт в разработке осветительных опор, металлических конструкций для рекламы, пластиковой тары, оснастки для литьевого производства.</p>
		<p>Разрабатываю технические условия на товары народного потребления, сопроводительную документацию (паспорта, инструкции по эксплуатации, технические описания, технические задания).</p>
		<p>Надеюсь, мои знания и опыт помогут развить Ваш бизнес в сфере производства осветительного оборудования, металлических конструкций, пластиковой тары и других товаров народного потребления.</p>"

		buttonText  = "Услуги"


	# Service section
	[params.services]
		headline = "Предоставляемые услуги"
		buttonText = "Контакты"

        [[params.services.list]]
            icon = "fa-file-text"
            title = "Разработка конструкторской и сопроводительной документации"

        [[params.services.list]]
			icon = "fa-pencil-square"
			title = "Изготовление чертежей"
			modalId = "blueprints"

		[[params.services.list]]
            icon = "fa-cube"
            title = "3D моделирование"

        [[params.services.list]]
            icon = "fa-globe"
            title = "Технический перевод"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	#[params.aside]
	#	headline = "Get the Creative Theme for Hugo"
	#
	#	[params.aside.button]
	#		text = "Download now"
	#		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Контакты"
		description = "Свяжитесь со мной"
		phone = "+375(29) 379-51-81"
		email = "bobs59@mail.ru"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
